project_id = "nuaqnxskrudgwcnfmnnk"

[functions.scrape-agency-website]
verify_jwt = true

[functions.generate-adaptive-query]
verify_jwt = true

[functions.transform-article]
verify_jwt = true

[functions.bulk-extract-entities]
verify_jwt = true

[functions.discover-articles]
verify_jwt = true

[functions.agentic-review]
verify_jwt = true

[functions.generate-targeted-searches]
verify_jwt = true

[functions.execute-automated-searches]
verify_jwt = false

[functions.process-search-results]
verify_jwt = false

[functions.find-agency-procurement]
verify_jwt = false

[functions.transform-report]
verify_jwt = true

[functions.import-transportation-providers]
verify_jwt = true
